home:
  uri: /home/
  controller: HomeController
  action: index
ingredients:
  uri: /ingredients/
  controller: IngredientsController
  action: index
setcategory:
  uri: /setcategory/
  controller: AjaxController
  action: setCategory
settings:
  uri: /settings/
  controller: SettingsController
  action: index
delete-ingredient:
  uri: /delete-ingredient/
  controller: AjaxController
  action: deleteIngredient
dishes:
  uri: /dishes/
  controller: DishesController
  action: index
setComplexityLevel:
  uri: /setComplexityLevel/
  controller: AjaxController
  action: setComplexityLevel
setMaxTime:
  uri: /setMaxTime/
  controller: AjaxController
  action: setMaxTime
menu-maker:
  uri: /menu-maker/
  controller: MenuMakerController
  action: index
delete-dish:
  uri: /delete-dish/
  controller: AjaxController
  action: deleteDish
add-ingredients:
  uri: /add-ingredients/
  controller: DishesController
  action: addIngredients
delete-ingredient-from-dish:
  uri: /delete-ingredient-from-dish/
  controller: AjaxController
  action: deleteIngredientFromDish
add-ingredient-to-dish:
  uri: /add-ingredient-to-dish/
  controller: AjaxController
  action: addIngredientToDish
delete-unit:
  uri: /delete-unit/
  controller: AjaxController
  action: deleteUnit
update-unit:
  uri: /update-unit/
  controller: AjaxController
  action: updateUnit
save-new-unit:
  uri: /save-new-unit/
  controller: AjaxController
  action: saveNewUnit
change-menu-of-the-day:
  uri: /change-menu-of-the-day/
  controller: AjaxController
  action: changeMenuOfTheDay
check-for-existing-date:
  uri: /check-for-existing-date/
  controller: AjaxController
  action: checkForExistingDate
add-menu-item:
  uri: /add-menu-item/
  controller: AjaxController
  action: addMenuItem
delete-menu-item:
  uri: /delete-menu-item/
  controller: AjaxController
  action: deleteMenuItem
shopping-list:
  uri: /shopping-list/
  controller: ShoppingListController
  action: index
inspiration:
  uri: /inspiration/
  controller: InspirationController
  action: index
add-new-ingredient:
  uri: /add-new-ingredient/
  controller: AjaxController
  action: AddNewIngredient